# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('BRO', 'Bronx'), ('BRK', 'Brooklyn'), ('QNS', 'Queens'), ('MAN', 'Manhattan'), ('STN', 'Staten Island')], default=datetime.datetime(2016, 4, 14, 6, 18, 51, 433533, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
    ]
