# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auto_20160414_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('GN', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], default='GN', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('BRO', 'Bronx'), ('BRK', 'Brooklyn'), ('QNS', 'Queens'), ('MAN', 'Manhattan'), ('STN', 'Staten Island')], default='BRO', max_length=3),
        ),
    ]
