# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='option_name',
            field=models.CharField(default='Scholarship', max_length=200),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_amount',
            field=models.IntegerField(default=0),
        ),
    ]
