# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0012_auto_20160415_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option_state',
            field=models.CharField(choices=[('Maharastra', 'Maharastra'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('West Bangal', 'West Bangal')], default='MH', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('Maharastra', 'Maharastra'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('West Bangal', 'West Bangal')], default='MH', max_length=10),
        ),
    ]
