# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0014_auto_20160415_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('GN', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('Maharastra', 'Maharastra'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('West Bangal', 'West Bangal')], max_length=20),
        ),
    ]
